### ISSUE TITLE
add support for activity_copy_limit to follow_many

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-ruby#33]

**Comment by kennym** [comment]
I want to make use of limiting the activities upon following via the batch request, however I've hit a roadblock for a possible patch because of your API design.

Would you be able to update your API to assign the list to a variable like `follows` for the `follow_many` endpoint, so I can pass a `Hash` to the POST request. As of right now I cannot pass an `activity_copy_limit` along with the API request, because your endpoint expects to receive a list for the non-field parameter.

So, I want data for the POST request to look like:

```
{
   follows: [{source: "", target: ""}],
   activity_copy_limit: 4,
}
```

instead of

```
[{source: "", target: ""}]
```

**Comment by kennym** [comment]
I suggest that your endpoint allows both payloads (a list and a hash), so you don't break backward-compatibility with the previous API design.

**Comment by kennym** [comment]
^^^ @tbarbugli @tschellenbach

**Comment by tbarbugli** [comment]
This should be enough (need more testing before releasing it) https://github.com/GetStream/stream-ruby/commit/9392986ee167ca84af2f3047d1ff7ab47c1732e6

**Comment by kennym** [comment]
thanks :+1:
