### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-ruby#60]
Users have reported `Net::ReadTimeout` or `Net::OpenTimeout` in rare cases. Maybe our connection defaults can be improved?

**Comment by tbarbugli** [comment]
this seems to be related to using `persistent_http` for keep-alive with default settings. Default settings: connection pool with 1 connection and `pool_timeout` unset. I did not check but I guess it means that acquiring a connection raises an error instead of blocking when the pool is exhausted.

We should probably expose `pool_size` and `pool_timeout` as options and use better defaults (eg. `2` and `0.2`)

**Comment by tbarbugli** [comment]
in stream-rails: https://github.com/GetStream/stream-rails/blob/master/lib/stream_rails.rb#L16 we probably re-use the same client and potentially share it across different threads

**Comment by iandouglas** [comment]
I believe the `persistent_connection_adapater` can only be initialized outside of a method (I haven't been able to move it into StreamHTTPClient's initialize() method successfully yet), which means the settings values for pool size etc would either need to be globals or environment settings, which seems pretty hacky. I'm looking into a few other things.

**Comment by iandouglas** [comment]
Per internal conversation, persistence is removed pending a switch from HTTParty to another more performant library.

**Comment by tschellenbach** [comment]
Kitsu guys: I'd love if it used Faraday, so we could plug in our HTTP library of choice (Typheous)
